notifications:
    email: false

language: python
python:
    - 2.7

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - echo ~/.haxe/lib | haxelib setup
    - haxelib install openfl || true
    - haxelib install openfl-tools || true
    - haxelib install openfl-native || true
    - haxelib install openfl-html5 || true
    - haxelib install openfl-compatibility || true
    - haxelib install munit || true
    - haxelib install hamcrest || true
    - haxelib install box2d || true
    - haxelib install nape || true
    - haxelib install tilelayer || true
    - haxe -version
    - haxelib run openfl

after_script:
    - ls

script: "haxe -cp src -main As3ToHaxe -neko bin/As3ToHaxe.n"